% compares two matrices by transforming a set of points by each matrix. the
% average difference in the transformed points is returned as the difference 
% between the matrices

%Input: two files paths to the .xml files generated by fcal

%Output: a vector of three numbers representing the difference in the
%matrices

function[avgDis] = CompareMatrix(file1, file2)

%Get the two Image-to-Probe matrices
    matrix1 = readFile(file1);
    matrix2 = readFile(file2);

%Corner points of an image at depth 5.5
    points = [210,20,0,1; 600,20,0,1; 210,600,0,1; 600,600,0,1]';

%Transform points by each matrix
    transformed1 = matrix1 * points;

    transformed2 = matrix2 * points;

    
%Find average distance between the two sets of transformed points
    avgDis = [0;0;0];
    for i=1:4
        avgDis = avgDis + (transformed1(1:3,i) - transformed2(1:3,i));
    end

    avgDis = avgDis/4;
end